{% set name = "autogluon" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 42e4838bb95328cedb54a9d094072068d8ce1e610a1154f91190b3670011561b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./autogluon -vv
  number: 0
  script_env:
    - RELEASE=1

requirements:
  host:
    - python {{ python_min }} 
    - pip
  run:
    - python >={{ python_min }}
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}
    - autogluon.tabular =={{ version }}
    - autogluon.multimodal =={{ version }}
    - autogluon.timeseries =={{ version }}

test:
  imports:
    - autogluon
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shchur
    - suzhoum
    - Innixma
    - prateekdesai04
