{% set name = "autogluon" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f10b1ab4cb33a1b0c6b626a2e99c471bf892626e315adcb95f2fe3c495b48448

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./autogluon -vv
  number: 0
  script_env:
    - RELEASE=1

requirements:
  host:
    - python >=3.8,<3.12
    - pip
  run:
    - python >=3.8,<3.12
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}
    - autogluon.tabular =={{ version }}
    - autogluon.multimodal =={{ version }}
    - autogluon.timeseries =={{ version }}

test:
  imports:
    - autogluon
  # commands:
  #   - python -c "from autogluon.version import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tonyhoo
    - suzhoum
    - yinweisu
    - Innixma
    - giswqs
