{% set name = "autogluon" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 455831de3c9de8fbe11b100054b8f150661d0651212fcfa4ec2e42417fdac355

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./autogluon -vv
  number: 0
  script_env:
    - RELEASE=1

requirements:
  host:
    - python >=3.7,<3.10
    - pip
  run:
    - python >=3.7,<3.10
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}
    - autogluon.tabular =={{ version }}
    - autogluon.multimodal =={{ version }}
    - autogluon.text =={{ version }}
    - autogluon.vision =={{ version }}
    - autogluon.timeseries =={{ version }}

test:
  imports:
    - autogluon
  commands:
    - python -c "from autogluon.version import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Innixma
    - giswqs
