{% set name = "autogluon" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/7dead13ee1efdffe437e0dc0b83ba08eb9dcf6c7.tar.gz
  sha256: 5cf3c86a6cac944fd070c17288753788a450eb2732b237d57686546d472f0ba5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./autogluon -vv
  number: 3
{% if variant == "light" %}
  string: "{{ variant }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"
{% endif %}
  script_env:
    - RELEASE=1

requirements:
  host:
    - python >=3.8,<3.11
    - pip
  run:
    - python >=3.8,<3.11
  {% if variant == "light" %}
    - autogluon.core =={{ version }}=*light*
  {% else %}
    - autogluon.core =={{ version }}
    - autogluon.timeseries =={{ version }}
  {% endif %}
    - autogluon.features =={{ version }}
    - autogluon.tabular =={{ version }}
    - autogluon.multimodal =={{ version }}

test:
  imports:
    - autogluon
  # commands:
  #   - python -c "from autogluon.version import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yinweisu
    - Innixma
    - giswqs
